# Multivariate Naive Bayes Classifier 


####  Taking Two Attributes Only

In [1]:
import pandas as pd
from math import e
import numpy as np
import scipy.stats as s
import random
import matplotlib.pyplot as plt

In [2]:
dataset = pd.read_csv("data.csv")
dataset.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

      ...       texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0     ...               17.33           184.60      2019.0            0.1622   
1     ...               23.41           158.80      1956.0            0.1238   
2     ...               25.53           152.50      1709.0            0.1444   
3     ...               26.50            98.87       567.7            0.2098   
4     ...               16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [3]:
data  =  dataset.iloc[0:,1:4]
data

diagnosis  radius_mean  texture_mean
0           M       17.990         10.38
1           M       20.570         17.77
2           M       19.690         21.25
3           M       11.420         20.38
4           M       20.290         14.34
5           M       12.450         15.70
6           M       18.250         19.98
7           M       13.710         20.83
8           M       13.000         21.82
9           M       12.460         24.04
10          M       16.020         23.24
11          M       15.780         17.89
12          M       19.170         24.80
13          M       15.850         23.95
14          M       13.730         22.61
15          M       14.540         27.54
16          M       14.680         20.13
17          M       16.130         20.68
18          M       19.810         22.15
19          B       13.540         14.36
20          B       13.080         15.71
21          B        9.504         12.44
22          M       15.340         14.26
23          M       21.160         23.04
24          M       16.650         21.38
25          M       17.140         16.40
26          M       14.580         21.53
27          M       18.610         20.25
28          M       15.300         25.27
29          M       17.570         15.05
..        ...          ...           ...
539         B        7.691         25.44
540         B       11.540         14.44
541         B       14.470         24.99
542         B       14.740         25.42
543         B       13.210         28.06
544         B       13.870         20.70
545         B       13.620         23.23
546         B       10.320         16.35
547         B       10.260         16.58
548         B        9.683         19.34
549         B       10.820         24.21
550         B       10.860         21.48
551         B       11.130         22.44
552         B       12.770         29.43
553         B        9.333         21.94
554         B       12.880         28.92
555         B       10.290         27.61
556         B       10.160         19.59
557         B        9.423         27.88
558         B       14.590         22.68
559         B       11.510         23.93
560         B       14.050         27.15
561         B       11.200         29.37
562         M       15.220         30.62
563         M       20.920         25.09
564         M       21.560         22.39
565         M       20.130         28.25
566         M       16.600         28.08
567         M       20.600         29.33
568         B        7.760         24.54

[569 rows x 3 columns]

In [4]:
Bdata = data[data['diagnosis'] == 'B']
Mdata = data[data['diagnosis'] == 'M']

BTrainData = Bdata[:200]
MTrainData = Mdata[:200]


In [5]:
PCapB = 200/400
PCapB

0.5

In [6]:
PCapBComplement =  1 - PCapB
PCapBComplement

0.5

In [7]:
CovarianceMatB = BTrainData.cov()
CovarianceMatB = np.array(CovarianceMatB)
CovarianceMatB

array([[ 2.9276847 ,  0.15383955],
       [ 0.15383955, 11.27652514]])

In [8]:
CovarianceMatM = MTrainData.cov()
CovarianceMatM = np.array(CovarianceMatM)
CovarianceMatM

array([[10.17591857,  1.25314218],
       [ 1.25314218, 13.89054569]])

In [9]:
MuCapB = BTrainData.mean()
MuCapB = np.array(MuCapB)
MuCapB.reshape(2,1)

array([[11.987175],
       [17.1157  ]])

In [10]:
MuCapM = np.array(MTrainData.mean())
MuCapM.reshape(2,1)

array([[17.34485],
       [21.4498 ]])

In [11]:
BTestData = Bdata[200:]
MTestData = Mdata[200:]

PBebignTumorB = s.multivariate_normal.pdf(BTestData.iloc[0:,1:3],MuCapB,CovarianceMatB,allow_singular = 1)
PMalignantTumorB = s.multivariate_normal.pdf(BTestData.iloc[0:,1:3],MuCapM,CovarianceMatM,allow_singular = 1)

PBebignTumorM = s.multivariate_normal.pdf(MTestData.iloc[0:,1:3],cov=CovarianceMatB,mean= MuCapB,allow_singular = 1)
PMalignantTumorM = s.multivariate_normal.pdf(MTestData.iloc[0:,1:3],cov=CovarianceMatM,mean= MuCapM,allow_singular = 1)


In [12]:
num1 = PBebignTumorB * PCapB
num2 = PMalignantTumorB * PCapBComplement

num3 = PBebignTumorM * PCapB
num4 = PMalignantTumorM * PCapBComplement

In [13]:
PredictBTest = num1/(num1+num2)

truenegative = 0
falsepositive = 0
for i in PredictBTest:
    if i >= 0.5:
        truenegative += 1
    else:
        falsepositive += 1
        
PredictedMTest = num3/(num3+num4)

truepositive = 0
falsenegative = 0

for i in PredictedMTest:
    if i >= 0.5:
        truepositive += 1
    else:
        falsenegative += 1
                
print("truenegative: ", truenegative, "falsepositive: ",falsepositive, "truepositive: ", truepositive, "falsenegative: ", falsenegative)
print("Total Benign Tumor: ", len(BTestData))
print("Total Malignant Tumor: ",len(MTestData))

accuracy = (truepositive + truenegative)/(len(BTestData)+len(MTestData))
print("Accuracy: ",accuracy)

truenegative:  125 falsepositive:  32 truepositive:  0 falsenegative:  12
Total Benign Tumor:  157
Total Malignant Tumor:  12
Accuracy:  0.7396449704142012


# Taking all the attributes

In [14]:
CData = dataset.iloc[0:,1:32]
# print(CData)
CBData = CData[CData['diagnosis'] == 'B']
CMData = CData[CData['diagnosis'] == 'M']

CBTrainData = CBData[0:200]
CMTrainData = CMData[0:200]

CBTestData = CBData[200:]
CMTestData = CMData[200:]

TrainData = CBTrainData.append(CMTrainData)
TestData = CBTestData.append(CMTestData)

In [15]:
from sklearn.naive_bayes import MultinomialNB

In [16]:
classifier = MultinomialNB()
classifier.fit(TrainData.iloc[0:,1:],TrainData['diagnosis'])

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [17]:
predictions = classifier.predict(TestData.iloc[0:,1:31])
predictions = predictions == TestData['diagnosis']
t = 0
for i in predictions:
    if i == True:
        t += 1
print(t)

163


In [18]:
predictions = classifier.predict(TestData.iloc[0:,1:31])

truepositiveCount = 0
truenegativeCount = 0

for i in range(1,len(predictions)):
    if predictions[i] == TestData.iloc[i,0]:
        if i == 'B':
            truepositiveCount += 1
        else:
            truenegativeCount += 1
            
print(truepositiveCount,truenegativeCount)


        

0 162
